/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CustomerServiceWeekRouteImport } from './routes/customer-service-week'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AgnesRouteImport } from './routes/agnes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as TeamAgnesNyawiraRouteImport } from './routes/team.agnes-nyawira'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceWeekRoute = CustomerServiceWeekRouteImport.update({
  id: '/customer-service-week',
  path: '/customer-service-week',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgnesRoute = AgnesRouteImport.update({
  id: '/agnes',
  path: '/agnes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAgnesNyawiraRoute = TeamAgnesNyawiraRouteImport.update({
  id: '/team/agnes-nyawira',
  path: '/team/agnes-nyawira',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agnes': typeof AgnesRoute
  '/careers': typeof CareersRoute
  '/customer-service-week': typeof CustomerServiceWeekRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/team/agnes-nyawira': typeof TeamAgnesNyawiraRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agnes': typeof AgnesRoute
  '/careers': typeof CareersRoute
  '/customer-service-week': typeof CustomerServiceWeekRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/team/agnes-nyawira': typeof TeamAgnesNyawiraRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agnes': typeof AgnesRoute
  '/careers': typeof CareersRoute
  '/customer-service-week': typeof CustomerServiceWeekRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/team/agnes-nyawira': typeof TeamAgnesNyawiraRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agnes'
    | '/careers'
    | '/customer-service-week'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/insights/$slug'
    | '/practice/$slug'
    | '/team/agnes-nyawira'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agnes'
    | '/careers'
    | '/customer-service-week'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/insights/$slug'
    | '/practice/$slug'
    | '/team/agnes-nyawira'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/agnes'
    | '/careers'
    | '/customer-service-week'
    | '/disclaimer'
    | '/faq'
    | '/privacy'
    | '/insights/$slug'
    | '/practice/$slug'
    | '/team/agnes-nyawira'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgnesRoute: typeof AgnesRoute
  CareersRoute: typeof CareersRoute
  CustomerServiceWeekRoute: typeof CustomerServiceWeekRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  TeamAgnesNyawiraRoute: typeof TeamAgnesNyawiraRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service-week': {
      id: '/customer-service-week'
      path: '/customer-service-week'
      fullPath: '/customer-service-week'
      preLoaderRoute: typeof CustomerServiceWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agnes': {
      id: '/agnes'
      path: '/agnes'
      fullPath: '/agnes'
      preLoaderRoute: typeof AgnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/agnes-nyawira': {
      id: '/team/agnes-nyawira'
      path: '/team/agnes-nyawira'
      fullPath: '/team/agnes-nyawira'
      preLoaderRoute: typeof TeamAgnesNyawiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgnesRoute: AgnesRoute,
  CareersRoute: CareersRoute,
  CustomerServiceWeekRoute: CustomerServiceWeekRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  TeamAgnesNyawiraRoute: TeamAgnesNyawiraRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
